### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by eightHundreds** [lanten/swagger-to-types#12]
报错信息

fetch: xxxx - FetchError: request to xxxx  failed, reason: socket hang up

能确定swagger地址可访问,无鉴权

只会在vscode启动时候会报这个错误.

第二个问题:

我的swagger api有部分地方有格式错误,这个插件解析失败,但是插件并不会给任何提示信息,vscode的输出面板也不会出现错误.

建议在catch回调里将错误打印出来

**Comment by lanten** [comment]
@eightHundreds 你好，应该是 bug，

fetch 相关的代码在[此处](https://github.com/lanten/swagger-to-types/blob/master/src/core/data-fetch.ts)，一个简单的 get 请求，你是否确认过你的地址可以请求通过？

能否给我一个可在公网访问的 swagger 地址用于调试，或者是一个相同格式的 json

**Comment by eightHundreds** [comment]
> 能否给我一个可在公网访问的 swagger 地址用于调试，或者是一个相同格式的 json

这个不能给,但是我能用 `openapi-typescript`成功解析. 你可以考虑下swagger解析逻辑复用它的

**Comment by eightHundreds** [comment]
> > 能否给我一个可在公网访问的 swagger 地址用于调试，或者是一个相同格式的 json
> 
> 这个不能给,但是我能用 `openapi-typescript`成功解析. 你可以考虑下swagger解析逻辑复用它的

你似乎解决了这个问题
