### ISSUE TITLE
[优化] 建议打开某个接口的类型详情不创建新tab

### ISSUE THREAD

**Issue by eightHundreds** [lanten/swagger-to-types#15]
现状:
点击某个接口类型会打开新的tab,关闭时vscode又会询问是否保存
点击查看多个接口时会打开多个tab,一个个关闭比较麻烦

建议:
建议一次只打开一个
建议参考gistpad的实现

![image](https://user-images.githubusercontent.com/18695431/103327404-5adace80-4a8f-11eb-86ab-5774fb6134bc.png)

**Comment by lanten** [comment]
认同你的想法，将在下个版本优化

**Comment by lanten** [comment]
这个问题先挂起，技术上暂时没有找到可行方案。

每次浏览在线接口的时候，打开的是一个临时文档，不同接口路径不同。由于这时间，实际文件还没有保存，所以会一直新开。

浏览本地接口时不存在这个问题。

或许我遗漏了某些文档，i need help!

**Comment by eightHundreds** [comment]
```
commands.executeCommand("vscode.open", uri, {
    preview: true, 
    viewColumn: ViewColumn.Active
  });
```

这个试过吗

**Comment by lanten** [comment]
此问题已在1.1.4版本中解决。
