### ISSUE TITLE
这个怎么获取接口？

### ISSUE THREAD

**Issue by WangJunZzz** [lanten/swagger-to-types#17]
![image](https://user-images.githubusercontent.com/25657426/114361019-476bf300-9ba8-11eb-86d8-389218400aee.png)

**Comment by WangJunZzz** [comment]
通过浏览器可以访问json
![image](https://user-images.githubusercontent.com/25657426/114361166-679bb200-9ba8-11eb-8b6b-9a712221216f.png)

**Comment by lanten** [comment]
当前解析器只支持 v2 版本的 swagger API，你这个看上去是 v1。

**Comment by lanten** [comment]
这个官方demo 可以通过测试： https://petstore.swagger.io/v2/swagger.json

**Comment by WangJunZzz** [comment]
了解了 我这个是openapi 3.0的版本 不支持、、
