### ISSUE TITLE
给定链接出现报错

### ISSUE THREAD

**Issue by AKclown** [lanten/swagger-to-types#20]
使用插件时出现如下报错是什么原因？
![image](https://user-images.githubusercontent.com/33648653/141234778-b2807905-07d8-444d-90aa-7d4262a8d2c4.png)

**Comment by lanten** [comment]
看上去是模块导入失败，能否提供一下运行环境和 vscode 版本信息

**Comment by AKclown** [comment]
vscode版本
Version: 1.62.1 (user setup)
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T10:57:55.946Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

平台
windows10

**Comment by lanten** [comment]
破案了，修复这个链接试一下
![image](https://user-images.githubusercontent.com/16203518/141263405-a10871b1-daed-4459-b79c-93e68b2d5c73.png)

**Comment by AKclown** [comment]
找到了原因， 在https前面有空格，早上没注意到。谢谢了
