### ISSUE TITLE
能否也添加一个文件名的模板函数

### ISSUE THREAD

**Issue by lx11573** [lanten/swagger-to-types#22]
通过模板可以自定义 namespace
那么能否也添加一个文件名的模板函数

**Comment by lanten** [comment]
插件有时候需要通过某种约定好的格式来找到相应的文件，如果文件名可配置，那这个步骤必须先去调用模板函数，这会增加很多复杂度。

存放 .d.ts 文件的目录在 tsconfig 中引用后，会自动全局加载，自定义文件名的意义似乎不大。

我觉得实现这个功能可能不太划算。
